version: '3.8'

services:
  flask_app:
    container_name: flask_app
    image: flask_app
    build: ./chatbot/
    restart: always
    ports:
      - "5000:5000"

  django_app:
    container_name: django_app
    image: django_app
    build: ./chatbot_project/
    restart: always
    ports:
      - "8000:8000"

volumes:
  apps:



